import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";

import "./globals.css";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
const inter = Inter({ subsets: ["latin"] });

import Navbar from "./components/navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          <div className="flex flex-col min-h-screen">
            <div className="grow-0">{children}</div>
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
